# Numpy practice

After going through the [Intro_to_numpy notebook](intro_to_numpy.ipynb) complete the exercises below.

To help you out, here's an array of numpy methods often used in the DSI.

```python
import numpy as np

lst = [4, 1, 2, 6, 5, 3]

mtrx_A = [ [3, 2, 4],
           [1, 9, 0],
           [2, 8, 5] ]

# make a numpy array
a1 = np.array(lst) #convert a list to a numpy array
a2 = np.arange(0,12,2) #usually used for integers
a3 = np.linspace(1, 5, num=10, endpoint=True) # usually used for floats
a4 = np.array(mtrx_A)

# see the number of rows and columns in an array
shape_a1 = a1.shape
rows_a1 = a1.shape[0]
cols_a1 = a1.shape[1] # will return an error

# change the shape of an array
a1 = a1[:,np.newaxis] # makes a1 a column vector
cols_a1 = a1.shape[1] # now it does not throw an error, a1 has 1 column
a1 = a1.reshape((-1,1)) # so does this, the -1 is telling numpy to figure out the number of rows
a2.resize((3,2)) # does it inplace (note don't need a2 = a2.resize etc., asking for 2 columns

# math functions 
m1 = a1.mean() # average of entire array
m1_anotherway = np.mean(a1) # same
m4 = a4.mean() # average of entire array
m4_col_mn = a4.mean(axis = 0) # the average of each column
m4_row_mn = a4.mean(axis = 1) # the average of each row
m4_row_sum = a4.sum(axis = 1) # the sum of each row

# sorting
a1 = np.array(lst) #re-make array
a1.sort() #will sort along the longest axis, note that this is done inplace (don't need a1 = a1.sort())
a1 = a1[::-1] # reverse array order (high to low)
a4.sort(axis = 0) # columns sorted in ascending order, inplace
a4.sort(axis = 1) # rows sorted in ascending order, inplace

# working with array indices
cols = np.array(['A','B','C']) # column labels
rows = np.array(['Zeroth','First','Second','Third']) # row labels
mtrx_B = [ [3, -1, 0],
           [1, 10, 2],
           [4, -3, 9],
           [9, 11, 1] ]
indices_col_mins = np.argmin(mtrx_B, axis=0) # index of minimum value in each column
indices_row_mins = np.argmin(mtrx_B, axis=1) # index of minimum value in each row
(ind_row_min, ind_col_min) = np.where(mtrx_B == np.min(mtrx_B)) # find the row, column index of min. value
# now use indices to return the row and column labels of the minimum
print("The minimum occurs in the {0} row, {1} column.".format(rows[i_row_min][0],cols[i_col_min][0]))

```


### Question 1

Make the following matrices in numpy:

```python
arr1 = -0.2, 1.2, 3.4, 0.2

arr2 = 5  2  -3  2  
       0  3  12  3  
       2  9  10  6
```

In [9]:
import numpy as np

arr1 = np.array([-0.2, 1.2, 3.4, 0.2])
arr2 = np.array([[5,2,-3,2],[0,3,12,3], [2,9,10,6]]) 

print(arr1)
print(arr2)

[-0.2  1.2  3.4  0.2]
[[ 5  2 -3  2]
 [ 0  3 12  3]
 [ 2  9 10  6]]


### Question 2

a) Change each array into 1 row with as many columns as necessary.  
b) Change each array into 1 column with as many rows as necessary.

In each case save the reshaped array into a different variable name.

In [17]:

a1 = arr1.reshape((1,-1))
print(a1, a1.shape)
a2 = arr2.reshape((1,-1))
print(a2, a2.shape)

(4,)
(3, 4)
[[-0.2  1.2  3.4  0.2]] (1, 4)
[[ 5  2 -3  2  0  3 12  3  2  9 10  6]] (1, 12)


### Question 3

Find the array min, max, the row min, max, and the column min, max for `arr1` and `arr2`.

In [26]:
a1min_t = arr1.min()
a1max_t = arr1.max()
#a1min_row = arr1.min(axis = 1) there is only one row
#a1max_row = arr1.max(axis = 1) there is only one row
a1min_col = arr1.min(axis = 0)
a1max_col = arr1.max(axis = 0)
print(arr1)
print(a1min_t, a1max_t, a1min_col, a1max_col)

a2min_t = arr2.min()
a2max_t = arr2.max()
a2min_row = arr2.min(axis = 1) 
a2max_row = arr2.max(axis = 1) 
a2min_col = arr2.min(axis = 0)
a2max_col = arr2.max(axis = 0)
print(arr2)
print(a2min_t, a2max_t, a2min_row, a2max_row, a2min_col, a2max_col)


[-0.2  1.2  3.4  0.2]
-0.2 3.4 -0.2 3.4
[[ 5  2 -3  2]
 [ 0  3 12  3]
 [ 2  9 10  6]]
-3 12 [-3  0  2] [ 5 12 10] [ 0  2 -3  2] [ 5  9 12  6]


### Question 4

Return `arr1` and `arr2` sorted low to high, and high to low, row-wise and column-wise.  

In [56]:
arr1=np.array([-0.2 ,1.2 ,3.4 ,0.2])
print(arr1, '\n')
arr1.sort()
print('sorted on longest axis (col)', '\n',arr1, '\n')
arr1_h2l=arr1[::-1]
print('reverse sort on longest axis (col)', '\n',arr1_h2l, '\n')
print('Can not sort on rows (only 1 row)','\n')


arr2 = np.array([[5,2,-3,2],[0,3,12,3], [2,9,10,6]]) 
print(arr2, '\n')

arr2.sort()
print('sorted on longest axis (rows)', '\n',arr2,'\n')

arr2_h2l = arr2[::-1]
print('reverse sort on longest axis (rows)', '\n',arr2_h2l,'\n')

arr2 = np.array([[5,2,-3,2],[0,3,12,3], [2,9,10,6]]) 
print('remake arr2', '\n', arr2, '\n')

arr2.sort(axis=0)
print('sort on column', '\n',arr2,'\n')

arr2_col_h2l = arr2[::-1]
print('reverse sort on column', '\n', arr2_col_h2l,'\n')


[-0.2  1.2  3.4  0.2] 

.sort() is sorted on longest axis (col) 
 [-0.2  0.2  1.2  3.4] 

reverse sort on longest axis (col) 
 [ 3.4  1.2  0.2 -0.2] 

Can not sort on rows (only 1 row) 

[[ 5  2 -3  2]
 [ 0  3 12  3]
 [ 2  9 10  6]] 

.sort() is sorted on longest axis (rows) 
 [[-3  2  2  5]
 [ 0  3  3 12]
 [ 2  6  9 10]] 

reverse sort on longest axis (rows) 
 [[ 2  6  9 10]
 [ 0  3  3 12]
 [-3  2  2  5]] 

remake arr2 
 [[ 5  2 -3  2]
 [ 0  3 12  3]
 [ 2  9 10  6]] 

sort on column 
 [[ 0  2 -3  2]
 [ 2  3 10  3]
 [ 5  9 12  6]] 

reverse sort on column 
 [[ 5  9 12  6]
 [ 2  3 10  3]
 [ 0  2 -3  2]] 



### Question 5

Find the row and column of the maximum value `arr1` and `arr2`.  Print them out nicely.

In [76]:
cols = np.array(['0th','1st','2nd','3rd']) # column labels
rows = np.array(['0th','1st','2nd','3rd']) # row labels
(ind_col_min) = np.where(arr1 == np.min(arr1))

print('arr1 \n',arr1,'\n')
#print('arr2 min column index', ind_col_min[0], '\n')
print("The minimum occurs in the {} column of the single row in arr1. \n".format(cols[ind_col_min][0]))

(ind2_row_min, ind2_col_min) = np.where(arr2 == np.min(arr2))
print('arr2 \n',arr2,'\n')
#print('arr2 min index', ind2_row_min, ind2_col_min, '\n')
print("The minimum occurs in the {} row, {} column in arr2. \n".format(rows[ind2_row_min][0],cols[ind2_col_min][0]))

arr1 
 [-0.2  0.2  1.2  3.4] 

The minimum occurs in the 0th column of the single row in arr1. 

arr2 
 [[ 0  2 -3  2]
 [ 2  3 10  3]
 [ 5  9 12  6]] 

The minimum occurs in the 0th row, 2nd column in arr2. 

